### ISSUE TITLE
fix nextjs-bundle-analysis.yml issue

### ISSUE THREAD

**Issue by james-gates-0212** [james-gates-0212/portfolio#87]
```yml
      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        if: success() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml # change to nextjs-bundle-analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base
```
